name: Lint

on: [push, pull_request]

concurrency:
  group: "${{ github.ref }}#${{ github.workflow}}"
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'
  NODE_VERSION: '18'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: true

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Lint script files
      run: npm run lint-scripts

  html-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: true

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Lint HTML files
      run: npm run lint-html

  styles-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: true

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Lint style files
      run: npm run lint-styles

  python-black-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/backend
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: pip install black

    - name: Lint python files
      run: black --check .
